name: Teleporta
description: Some useful commands for teleporting.
main: top.shjibi.teleporta.Main
version: ${project.version}
api-version: 1.16


commands:
  location:
    description: Tell everyone / someone your coordinate and world.
  tpa:
    description: send a teleport request to another player
  tpahere:
    description: send a teleport here request to another player
  tpaccept:
    description: accept one's teleport request
  tpadeny:
    description: deny one's teleport request
  tpacancel:
    description: recall your teleport request
  warp:
    description: add / remove / teleport to a warp point